### ISSUE TITLE
Check for updates automatically

### ISSUE THREAD

**Issue by jaimefeldman** [nbolar/PlayStatus#24] opened 2022-08-02 15:37 UTC
The automatic update query window does not close.
(macOS 12.5)

**Comment by nbolar** [comment] 2022-08-02 15:47
Hi @jaimefeldman. Can you please provide a screenshot of what it looks like? That sounds like more of a Sparkle(the third party framework used to manage updates) issue than a PlayStatus issue. Anyhow I will try figuring out what's causing it.

**Comment by nbolar** [comment] 2022-09-05 21:46
Closing this issue as no update provided and is not reproducible.

**Closed as completed by nbolar** 2022-09-05 21:46 UTC
