### ISSUE TITLE
PlayStatus not pulling track info/album art from Spotify

### ISSUE THREAD

**Issue by dscos** [nbolar/PlayStatus#10] opened 2020-04-22 20:08 UTC
Weird issue, not sure exactly when it started but I just noticed it — PlayStatus is not pulling track info or album art from Spotify. It pulls the track length and progress and the in-app media controls work, but the PlayStatus area shows only the Spotify icon and the album art area just shows the default picture of a dock on water.

Everything works fine with Apple Music.

Can you reproduce this or is my MacBook just insane?

**Comment by nbolar** [comment] 2020-04-22 20:17
That's very strange. I haven't been able to reproduce this. Is this behavior persistent through a restart of the app too?

**Comment by dscos** [comment] 2020-04-22 20:19
Yeah, through restarts of both PlayStatus and Spotify. If you can't reproduce though I'm sure it's something on my end. I'll try rebooting in a little while and update.

**Comment by nbolar** [comment] 2020-04-22 20:24
I'm currently working on an update and it should be ready in the next week or so but I've attached a beta build. I've added different menubar text options as requested. There are a few bugs but they should be ironed out soon. If you want to give it a go feel free to do so.

[PlayStatus.app.zip](https://github.com/nbolar/PlayStatus/files/4518831/PlayStatus.app.zip)

**Comment by dscos** [comment] 2020-04-22 20:27
Weirdly enough it finally loaded in the track info and album art, then I skipped tracks and it didn't load for the new track. LOL. I'll try the new build.

**Comment by dscos** [comment] 2020-04-22 20:35
Neither the new build or a restart helped. I'll try to troubleshoot and figure out if there's anything else I'm running that might conflict.

**Comment by nbolar** [comment] 2020-04-22 20:43
Okay that's unfortunate because I tried various different builds that I have as well as the latest official one and I haven't been able to replicate it. If you do manage to figure out what maybe conflicting with it please let me know. One app that may cause an issue is LuLu. If you're running it, it should show you a popup notifying you that PlayStatus is trying to download the artwork and if you accidentally clicked deny then that may be an issue but I can't be sure yet.

**Comment by dscos** [comment] 2020-04-22 20:46
Not running that app, but I running a Spotify notifications app and some apps that alter the menubar like Bartender, so I'll try closing those out and seeing if it makes a difference. 

Weirdly it is working randomly now. I was playing a song on repeat and the track info and art finally popped in during the third play in a row lol.

**Comment by nbolar** [comment] 2020-04-22 20:49
Oh okay wow, also I was wondering if you could give me any sort of feedback with the various menubar text options I included. Bugs or anything else in general would be great too! The non-scrollable options should drastically reduce memory usage.

**Comment by dscos** [comment] 2020-04-22 20:58
Is the desired behavior that if you turn off the scrollable text option, there's just nothing, no icon or text or anything?

**Comment by nbolar** [comment] 2020-04-22 21:17
Okay so there's good news and bad news. The good news is that I was able to finally reproduce the bug. The bad news, it looks like it is a Spotify - apple script issue. For some reason, Spotify isn't returning the artist and song name correctly. It some times does but the other times returns an empty string. I'll try searching for a workaround but I can't be sure of anything right now. 

So when you turn off the scrollable text option, it should show you the entire name of the song you're playing similar to SpotMenu. It requires an app restart to work properly.

**Comment by dscos** [comment] 2020-04-22 21:22
OK, turning off the scrollable text option is working correctly now. I thought I had restarted the app before, but I guess I didn't. Honestly the scrolling has grown on me, so I'm not sure which option I'll settle on, but I appreciate having the choice!

As far as the Spotify bug, glad you were able to reproduce it, sorry it's not something easy. Thanks for all your hard work on this app!

**Comment by nbolar** [comment] 2020-04-22 21:38
I'm glad to hear that. Thank you for all your feedback, I appreciate it very much!

So the bug gets weirder and is restricted to only Spotify. If you skip a song then it may/may not show the next song info however if you drag the slider to the end of the track, the next song loads just fine.

**Comment by dscos** [comment] 2020-04-22 22:22
Lol, weird! I wonder if Spotify changed something or what!

**Comment by nbolar** [comment] 2020-05-29 15:33
I think it works more reliably as of the recent version and so I'm closing this issue for now.

**Closed as completed by nbolar** 2020-05-29 15:33 UTC
Labels: bug
